/*

    Statement Level Triggers (More than 1 event)

*/


CREATE OR REPLACE TRIGGER customer_after_action
AFTER INSERT OR UPDATE OR DELETE
ON CUSTOMER
DECLARE
    V_USERNAME VARCHAR2(100);
BEGIN
    SELECT USER INTO V_USERNAME FROM DUAL;

    IF INSERTING THEN
        INSERT INTO AUDIT_TABLE(TABLE_NAME,USER_ID,OPERATION_DATE,OPERATION) VALUES('CUSTOMER',V_USERNAME,SYSDATE,'INSERT OPERATION');
    ELSIF DELETING THEN
        INSERT INTO AUDIT_TABLE(TABLE_NAME,USER_ID,OPERATION_DATE,OPERATION) VALUES('CUSTOMER',V_USERNAME,SYSDATE,'DELETING OPERATION');
    ELSIF UPDATING THEN
        INSERT INTO AUDIT_TABLE(TABLE_NAME,USER_ID,OPERATION_DATE,OPERATION) VALUES('CUSTOMER',V_USERNAME,SYSDATE,'uPDATING OPERATION');
    END IF;
END;

INSERT INTO CUSTOMER VALUES(15,'Ratn','Govindam','Pandey','Hajpurwa','Bihar','Samastipur','INDIA',SYSDATE,'NORTH');

DELETE FROM CUSTOMER WHERE CUSTOMER_ID=15;

select * from AUDIT_TABLE;
select * from CUSTOMER;