/*
    Row Level Triggers
        Execute once for each row in a transaction
*/

CREATE OR REPLACE TRIGGER CUSTOMER_AFTER_UPDATE
AFTER UPDATE ON CUSTOMER
FOR EACH ROW
DECLARE
    V_USERNAME VARCHAR2(100);
BEGIN
    SELECT USER INTO V_USERNAME FROM DUAL;

    INSERT INTO AUDIT_TABLE(TABLE_NAME,USER_ID,OPERATION_DATE,OPERATION) VALUES('CUSTOMER',V_USERNAME,SYSDATE,'Update row level');
END;

UPDATE CUSTOMER SET DATE_ADDED =SYSDATE WHERE REGION='SOUTH';
select * from AUDIT_TABLE;
select * from CUSTOMER;