/*
    Run this in your DB before working on Trigger
*/

CREATE TABLE AUDIT_TABLE
( 
    TABLE_NAME VARCHAR2(100),
    USER_ID VARCHAR2(100),
    OPERATION_DATE DATE,
    OPERATION VARCHAR2(100)
);

CREATE TABLE AUDIT_LOG
( 
    USERID VARCHAR2(100),
    OPERATION_DATE DATE,
    B_CUSTOMERID NUMBER,
    A_CUSTOMERID NUMBER,
    B_FIRSTNAME VARCHAR2(100),
    A_FIRSTNAME VARCHAR2(100)
);