-- comments in sql

DECLARE

BEGIN
    -- SINGLE LINE COMMENT IS USING --
    DBMS_OUTPUT.PUT_LINE('SINGLE LINE COMMENT IS USING --');
    -- MULTILINE COMMENT IS USING /* */
    DBMS_OUTPUT.PUT_LINE('MULTILINE COMMENT IS USING /* */');
END;
/